### ISSUE TITLE
change "block this site" to some icon

### ISSUE THREAD

**Issue by yonashub** [iorate/uBlacklist#159]
having "block this site" on each result entry is distracting. it is better to change it to some icon or unicode char to represent it.

**Comment by mo-san** [comment]
This is an ad hoc workaround, but you could use this CSS with Stylish browser extension:

```css
/* uBlacklist's "Block this site" */

#rso .ub-button
,#islmp .ub-button /* image search */
{
  font-size: 0;
}

#rso .ub-button:before
,#islmp .ub-button:before
{
  content: "🚫";  /*  &#x1f6ab; as html entity */
  font-size: small;
}
```
