### ISSUE TITLE
Exist unhidden divs

### ISSUE THREAD

**Issue by SunBK201** [iorate/ublacklist#270]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/49178170/190057876-483e4668-4f2e-4b64-8288-0a3f790323f9.png">

## Specifications

- OS: macOS 12
- Browser: Safari

**Comment by iorate** [comment]
**WON'T FIX:** The fix would be complicated and fragile while it is not a serious problem. Thank you for your report.

**Comment by SunBK201** [comment]
I have used userscript to hide the div: 
```css
.FxLDp:has(.MYVUIe .XN9cAe > div[data-ub-blocked]) {
    display: none;
}
```
It works, but still has flaws. When clicking to display an item that has been hidden by ublacklist, the div controlled by my userscript is not displayed.

**Comment by iorate** [comment]
@SunBK201 
To hide only results hidden by uBlacklist, you can use `[data-ub-blocked="hidden"]`:

```css
.FxLDp:has(.MYVUIe .XN9cAe > div[data-ub-blocked="hidden"]) {
    display: none;
}
```

---

`:has()` is a good idea. Thank you.

**Comment by SunBK201** [comment]
It seems that the first nested result item of search results has different behaviors. Space still exists for the first result.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/49178170/199871621-586bdf91-fcd2-4286-b5b5-93d22c36262b.png">

I solved it temporarily:
```css
.g:has(div > div[data-ub-blocked="hidden"]) {
    display: none;
}
```
