### ISSUE TITLE
[Feature Request] Icon instead of "Block this site"

### ISSUE THREAD

**Issue by lonix1** [iorate/ublacklist#279]
The "block this site" adds quite a lot of "noise" to the search results.

It would be nice to have an option to use an icon instead of text.

(A good example is the "Block or Highlight Search Engine Results" extension: https://addons.mozilla.org/en-US/firefox/addon/hohser)

**Comment by iorate** [comment]
It is true that a HoHSER-like UI would be cooler, but I have no plans to support it in the near future.

Please try user CSS instead:
```css
.ub-button {
  visibility: hidden;
}
.ub-button::before {
  visibility: visible;
  content: "😄"
}
```
