### ISSUE TITLE
[Feature Request] Add border colors to highlighted results

### ISSUE THREAD

**Issue by SunBK201** [iorate/ublacklist#280]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/49178170/194061780-7a2c0133-252d-41e4-85ed-5c8b95a6fc8a.png">

I have implemented it with Userscripts, I hope ublacklist can support it.
```css
[data-ub-highlight="1"] {
    border: 1px solid !important;
    border-radius: 10px !important;
}
```
