### ISSUE TITLE
Bing images feed not filtered

### ISSUE THREAD

**Issue by jonpsp** [iorate/uBlacklist#550]
## Expected Behavior

When I visit https://www.bing.com/images/feed or https://www.bing.com/images/ (which shows "Images to inspire" at the top), I expect that the sites in my blacklist will not appear.  The same is true if I click the link marked [More inspiring images](https://www.bing.com/inspire?FORM=IRPFED)

## Actual Behavior

No filtering is done.

## Steps to Reproduce the Problem

1. Visit https://www.bing.com/images/feed in Microsoft Edge
2. View the results
3. Click on [More inspiring images](https://www.bing.com/inspire?FORM=IRPFED)
4. View the results

## Specifications

- Browser: Microsoft Edge
- Other extensions/add-ons:

| ExtensionName | ExtensionVersion | ExtensionID
| --- | --- | --- |
| Enhancer for YouTube™ | | dlgfaleeejmphhnemjgiaekdbonkagkd |
| iD Strava Heatmap| | eglbcifjafncknmpmnelckombmgddlco | 
| VT4Browsers | | feklilkmifhginhfoogmgelcopaplodb | 
| Microsoft S/MIME | | gamjhjfeblghkihfjdpmbpajhlpmobbp |
| Web Scrobbler | | hhinaapppaileiechjoiifaancjggfjm | 
| Edge relevant text changes | | jmjflgjpcpepeafmmgdpfkogkghcpiha | 
| Microsoft Edge DevTools Enhancements | | kfbdpdaobnofkbopebjglnaadopfikhh | 
| Wayback Machine | | kjmickeoogghaimmomagaghnogelpcpn | 
| Consent-O-Matic | | mdjildafknihdffpkfmmpnpoiajfjnjd | 
| `__MSG_name__` | 2024.7.17 | mkejgcgkdlddbggjhhflekkondicpnop | 
| Don't F*** With Paste | | nkgllhigpcljnhoakjkgaieabnkmgdkb | 
| Fakespot Fake Amazon Reviews and eBay Sellers | | paijomiecdfnkmhejfglgpjnfaidklhi | 
| `__MSG_extensionName__` | 8.9.2 | pncfbmialoiaghdehhbnbhkkgmjanfhe | 

- Search engine: Bing
- Language: English UK
- Region: UK

**Comment by planetarian** [comment]
It also isn't working with regular bing web results. seems to be getting weird URLs from links that look like e.g. `https://www.w3schools.xn--com%20%20jsref%20%20met_document_query-ou2xla.../`

**Comment by alien-sunset** [comment]
also not working on qwant and Ecosia image searches using Firefox 135.0.1
sites that are specifically blocked still show up, and there is no "block site" link

**Comment by iorate** [comment]
This is not a search results page, so it's unlikely to be officially supported. However, you can handle this yourself using a custom SERPINFO. See [Other Search Engines](https://ublacklist.github.io/docs/advanced-features#other-search-engines) for screenshots showing how to open the SERPINFO Options page.

Here is an example SERPINFO for Bing Images Feed:

```yaml
name: Bing Images Feed

pages:
  - name: Feed
    matches:
      - https://www.bing.com/images
      - https://www.bing.com/images/feed
      - https://www.bing.com/images/feed?*
      - https://www.bing.com/inspire
      - https://www.bing.com/inspire?*
    results:
      - root: [upward, 1, ".iuscp"]
        url:
          - regexSubstitute
          - '"purl":"([^"]+)'
          - "\\1"
          - [attribute, "m", ".iusc"]
        props:
          title: [attribute, "title", "li > a"]
        button: [icon, { style: "top: 128px; right: 4px" }, ".iuscp"]
```
