### ISSUE TITLE
uBlacklist icon placement in Google Image Search interferes with Google Images Direct Link userscript

### ISSUE THREAD

**Issue by HaikenEdge** [iorate/ublacklist#618]
The circle with the line through it icon used for uBlacklist in Google Image search is currently placed in the upper right corner of a search result, which is the same location in the interact the arrow icon used by the Google Images Direct Link userscript to link directly to the image is, as shown in this screenshot:

![Image](https://github.com/user-attachments/assets/2322d8fe-1674-4c17-a319-6bfa41663bfc)

I'd like to be able to use both the uBlacklist extension and the Google Images Direct Link userscript; is there a way to make it so the icons don't overlap?

**Comment by iorate** [comment]
You can customize the extension’s behavior using “My SERPINFO”. Go to the options page > SERPINFO > My SERPINFO and paste the following:

```yaml
name: My SERPINFO
pages:
  - name: Google Image Search
    matches:
      - https://www.google.com/search?*
    results:
      - root: .ivg-i
        url: .EZAeBe
        props:
          title: .OSrXXb
        button: [inset, { top: 0, right: "24px" }]  # Move the button 24px to the left
```
