### ISSUE TITLE
Re-adding built-in support for Kagi

### ISSUE THREAD

**Issue by GeorgeIsInTheAir** [iorate/ublacklist#620]
Hi there 👋

I'm a developer at Kagi, and I noticed that built-in support for Kagi was removed in the latest update, with a note mentioning “development constraints (e.g., access restrictions or paywalls).”

I just wanted to reach out to get a bit more context on that. We'd love to bring built-in support back and are happy to help however we can.

We’d really appreciate any guidance on what you'd need from us to consider re-adding Kagi to the built-in list.

**Comment by iorate** [comment]
Hi,

With v9, I introduced a new system called **SERPINFO** to support various search engines in a unified way.  
You can find the specification here: [https://ublacklist.github.io/docs/serpinfo](https://ublacklist.github.io/docs/serpinfo)

The reason Kagi was removed is that adding and maintaining SERPINFO for Kagi would require me to pay for a Kagi subscription (since it's a paid service with only a limited free tier).  I'm not a Kagi user myself and don't intend to pay for this purpose.
Another reason (which I haven’t mentioned elsewhere) is that Kagi itself seems to provide a built-in domain block feature, so I’m not sure if uBlacklist is even necessary for Kagi users.

That said, if Kagi support in v8.12.0 was working for your current SERP layout (see [this file](https://github.com/iorate/ublacklist/blob/0cd1da6057147d31fcbab11c76e5f76a25f9e8d2/src/scripts/search-engines/kagi.ts)), the corresponding SERPINFO would probably look like this:

```yaml
name: Kagi
pages:
  - name: All
    matches:
      - https://kagi.com/search?*
      - https://kagi.com/images?*
      - https://kagi.com/videos?*
      - https://kagi.com/news?*
      - https://kagi.com/podcasts?*
    results:
      - root: ._ext_r
        url: ._ext_u
        props:
          title: ._ext_t
    delay: 400
```

As for options going forward:

- You could recommend users to add this to their My SERPINFO manually.
- Alternatively, you could host this SERPINFO on your server (GitHub is fine) and have users subscribe to it. 
- If you prefer, I’m open to including it in the built-in list (https://github.com/ublacklist/builtin), but only if you commit to maintaining it going forward.

Let me know which option works best for you.

**Comment by Chamiu** [comment]
> Hi,
> Kagi would require me to pay for a Kagi subscription (since it's a paid service with only a limited free tier). I'm not a Kagi user myself and don't intend to pay for this purpose. Another reason (which I haven’t mentioned elsewhere) is that Kagi itself seems to provide a built-in domain block feature, so I’m not sure if uBlacklist is even necessary for Kagi users.

Do you really have to bring up this kind of religious argument nowadays?  
"What is the price for providing a free service? Of course, it's to collect all the information of visiting users and sell it to third parties as material for fraud or sexual advertisements, turning it into revenue for the service provider, right?"

Since it was troublesome, I just did a [dead copy](https://raw.githubusercontent.com/Chamiu/Search-Block-Parasiticide/refs/heads/master/kagi.txt). Thankfully, it's working fine.

**Comment by iorate** [comment]
To get Kagi support implemented, I'll need you to create a pull request with the SERPINFO configuration. Here's what I need:

## 1. First, please create a PR to the [ublacklist/builtin](https://github.com/ublacklist/builtin) repository:

Add a new file `serpinfo/kagi.yml` with something like this:

```yaml
name: Kagi
homepage: https://github.com/ublacklist/builtin#readme
lastModified: 1970-01-01T00:00:00Z

pages:
 - name: All
   matches:
     - https://kagi.com/search?*
     - https://kagi.com/images?*
     - https://kagi.com/videos?*
     - https://kagi.com/news?*
     - https://kagi.com/podcasts?*
   results:
     - root: ._ext_r
       url: ._ext_u
       props:
         title: ._ext_t
   delay: 400
```

Please refer to our existing SERPINFO files and [documentation](https://ublacklist.github.io/docs/serpinfo) for guidance. I haven't tested this configuration yet, so please verify it works by pasting it into "My SERPINFO" (Options page > SERPINFO > My SERPINFO) before submitting the PR.

## 2. After that, create a second PR to the main uBlacklist repository:

This should update the `builtin` submodule and add the Kagi SERPINFO to [src/scripts/serpinfo/builtins.ts](https://github.com/iorate/ublacklist/blob/master/src/scripts/serpinfo/builtins.ts).
