### ISSUE TITLE
Support Google's dark theme

### ISSUE THREAD

**Issue by munierujp** [iorate/uBlacklist#81]
Google has started dark theme support.

<img width="492" alt="スクリーンショット 2021-02-10 20 59 53" src="https://user-images.githubusercontent.com/20086673/107507537-0de82d00-6be3-11eb-9616-dca41459cee2.png">

uBlacklist's current UI colors are not compatible with Google's dark theme.

<img width="1025" alt="スクリーンショット 2021-02-10 20 57 15" src="https://user-images.githubusercontent.com/20086673/107507259-a7630f00-6be2-11eb-8f02-76f61e059531.png">

<img width="1025" alt="スクリーンショット 2021-02-10 20 57 22" src="https://user-images.githubusercontent.com/20086673/107507496-fe68e400-6be2-11eb-9ca6-4e475b3df144.png">

## Colors

- background color: `#202124`
- link color: `#8ab4f8`

## How to determine if the current theme is dark

My idea is:

```js
function isDarkTheme () {
  const backgroundColor = window.getComputedStyle(document.body).backgroundColor
  const [, r, g, b] = backgroundColor.match(/\((\d+),\s*(\d+),\s*(\d+)\)/) 
  return r === '32' && g === '33' && b === '36'
}
```

**Comment by iorate** [comment]
@munierujp 
The dark mode has not come to me (all of my three accounts) even though I set the language and region to English/U.S.
It seems rolled out only to some users.

Would you tell me the implementation of the dark mode, or create a pull request to support it?
The link color of uBlacklist is defined as follows:
https://github.com/iorate/uBlacklist/blob/ad0a83ffe23fa5521f71909ad1851d25a4f69a6a/src/scripts/search-engines/google.ts#L11-L13
If the dark mode is implemented using CSS variables, for example,
```css
:root {
  --bg-color: '#202124';
  --link-color: '#8ab4f8';
}
```
we can simply use it.
```typescript
'.ub-button': { 
   color: 'var(--link-color, rgb(26, 13, 171))', 
 },
```

**Comment by munierujp** [comment]
@iorate 

>The dark mode has not come to me (all of my three accounts) even though I set the language and region to English/U.S.
It seems rolled out only to some users.

Oh, I see.

>Would you tell me the implementation of the dark mode, or create a pull request to support it?

As you may know, Google describes CSS in the HTML using `<style>` block.
The main differences between the light theme and the dark theme are as follows.

- light theme

```css
body {
  background: #fff;
  color: #202124;
}

a {
  color: #1a0dab;
  -webkit-tap-highlight-color: rgba(0, 0, 0, .10)
}

a:visited {
  color: #609
}
```

- dark theme

```css
body {
  background: #202124;
  color: #ddd;
}

a {
  color: #8ab4f8;
  -webkit-tap-highlight-color: rgba(255, 255, 255, .10)
}

a:visited {
  color: #8a8adb
}
```

>If the dark mode is implemented using CSS variables, for example,

Unfortunately, as mentioned above, it is not used.


I intend to create the PR, but if others want to do it, there is no reason to stop them 😎
